//go:build go1.22

// Package geodata provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package geodata

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for FeatureGeometryType.
const (
	FeatureGeometryTypePoint   FeatureGeometryType = "Point"
	FeatureGeometryTypePolygon FeatureGeometryType = "Polygon"
)

// Defines values for FeatureType.
const (
	FeatureTypeFeature FeatureType = "Feature"
)

// Defines values for FeatureCollectionType.
const (
	FeatureCollectionTypeFeatureCollection FeatureCollectionType = "FeatureCollection"
)

// Defines values for GeometryPointType.
const (
	GeometryPointTypePoint GeometryPointType = "Point"
)

// Defines values for GeometryPolygonType.
const (
	Polygon GeometryPolygonType = "Polygon"
)

// Feature defines model for Feature.
type Feature struct {
	Geometry   Feature_Geometry       `json:"geometry"`
	Properties map[string]interface{} `json:"properties"`
	Type       FeatureType            `json:"type"`
}

// FeatureGeometryType defines model for Feature.Geometry.Type.
type FeatureGeometryType string

// Feature_Geometry defines model for Feature.Geometry.
type Feature_Geometry struct {
	Type  FeatureGeometryType `json:"type"`
	union json.RawMessage
}

// FeatureType defines model for Feature.Type.
type FeatureType string

// FeatureCollection defines model for FeatureCollection.
type FeatureCollection struct {
	Features []Feature             `json:"features"`
	Type     FeatureCollectionType `json:"type"`
}

// FeatureCollectionType defines model for FeatureCollection.Type.
type FeatureCollectionType string

// GeometryPoint defines model for GeometryPoint.
type GeometryPoint struct {
	Coordinates []float64         `json:"coordinates"`
	Type        GeometryPointType `json:"type"`
}

// GeometryPointType defines model for GeometryPoint.Type.
type GeometryPointType string

// GeometryPolygon defines model for GeometryPolygon.
type GeometryPolygon struct {
	Coordinates [][][]float64       `json:"coordinates"`
	Type        GeometryPolygonType `json:"type"`
}

// GeometryPolygonType defines model for GeometryPolygon.Type.
type GeometryPolygonType string

// FeatureCollection200 defines model for FeatureCollection200.
type FeatureCollection200 = FeatureCollection

// GetDoorParams defines parameters for GetDoor.
type GetDoorParams struct {
	LevelId int `form:"level_id" json:"level_id"`
}

// GetLevelParams defines parameters for GetLevel.
type GetLevelParams struct {
	BuildingId int `form:"building_id" json:"building_id"`
}

// GetRoomParams defines parameters for GetRoom.
type GetRoomParams struct {
	LevelId int `form:"level_id" json:"level_id"`
}

// AsGeometryPolygon returns the union data inside the Feature_Geometry as a GeometryPolygon
func (t Feature_Geometry) AsGeometryPolygon() (GeometryPolygon, error) {
	var body GeometryPolygon
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGeometryPolygon overwrites any union data inside the Feature_Geometry as the provided GeometryPolygon
func (t *Feature_Geometry) FromGeometryPolygon(v GeometryPolygon) error {
	t.Type = "Polygon"

	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGeometryPolygon performs a merge with any union data inside the Feature_Geometry, using the provided GeometryPolygon
func (t *Feature_Geometry) MergeGeometryPolygon(v GeometryPolygon) error {
	t.Type = "Polygon"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGeometryPoint returns the union data inside the Feature_Geometry as a GeometryPoint
func (t Feature_Geometry) AsGeometryPoint() (GeometryPoint, error) {
	var body GeometryPoint
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGeometryPoint overwrites any union data inside the Feature_Geometry as the provided GeometryPoint
func (t *Feature_Geometry) FromGeometryPoint(v GeometryPoint) error {
	t.Type = "Point"

	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGeometryPoint performs a merge with any union data inside the Feature_Geometry, using the provided GeometryPoint
func (t *Feature_Geometry) MergeGeometryPoint(v GeometryPoint) error {
	t.Type = "Point"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Feature_Geometry) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Feature_Geometry) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "Point":
		return t.AsGeometryPoint()
	case "Polygon":
		return t.AsGeometryPolygon()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Feature_Geometry) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	object["type"], err = json.Marshal(t.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *Feature_Geometry) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &t.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
	}

	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Buildings
	// (GET /building)
	GetBuilding(w http.ResponseWriter, r *http.Request)
	// Get Doors
	// (GET /door)
	GetDoor(w http.ResponseWriter, r *http.Request, params GetDoorParams)
	// Get Levels
	// (GET /level)
	GetLevel(w http.ResponseWriter, r *http.Request, params GetLevelParams)
	// Get Rooms
	// (GET /room)
	GetRoom(w http.ResponseWriter, r *http.Request, params GetRoomParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetBuilding operation middleware
func (siw *ServerInterfaceWrapper) GetBuilding(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBuilding(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetDoor operation middleware
func (siw *ServerInterfaceWrapper) GetDoor(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDoorParams

	// ------------- Required query parameter "level_id" -------------

	if paramValue := r.URL.Query().Get("level_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "level_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "level_id", r.URL.Query(), &params.LevelId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "level_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDoor(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetLevel operation middleware
func (siw *ServerInterfaceWrapper) GetLevel(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLevelParams

	// ------------- Required query parameter "building_id" -------------

	if paramValue := r.URL.Query().Get("building_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "building_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "building_id", r.URL.Query(), &params.BuildingId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "building_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLevel(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetRoom operation middleware
func (siw *ServerInterfaceWrapper) GetRoom(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRoomParams

	// ------------- Required query parameter "level_id" -------------

	if paramValue := r.URL.Query().Get("level_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "level_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "level_id", r.URL.Query(), &params.LevelId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "level_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoom(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       *http.ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m *http.ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m *http.ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/building", wrapper.GetBuilding)
	m.HandleFunc("GET "+options.BaseURL+"/door", wrapper.GetDoor)
	m.HandleFunc("GET "+options.BaseURL+"/level", wrapper.GetLevel)
	m.HandleFunc("GET "+options.BaseURL+"/room", wrapper.GetRoom)

	return m
}

type BadRequest400Response struct {
}

type FeatureCollection200ApplicationGeoPlusJSONResponse FeatureCollection

type GetBuildingRequestObject struct {
}

type GetBuildingResponseObject interface {
	VisitGetBuildingResponse(w http.ResponseWriter) error
}

type GetBuilding200ApplicationGeoPlusJSONResponse struct {
	FeatureCollection200ApplicationGeoPlusJSONResponse
}

func (response GetBuilding200ApplicationGeoPlusJSONResponse) VisitGetBuildingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/geo+json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDoorRequestObject struct {
	Params GetDoorParams
}

type GetDoorResponseObject interface {
	VisitGetDoorResponse(w http.ResponseWriter) error
}

type GetDoor200ApplicationGeoPlusJSONResponse struct {
	FeatureCollection200ApplicationGeoPlusJSONResponse
}

func (response GetDoor200ApplicationGeoPlusJSONResponse) VisitGetDoorResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/geo+json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDoor400Response = BadRequest400Response

func (response GetDoor400Response) VisitGetDoorResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetLevelRequestObject struct {
	Params GetLevelParams
}

type GetLevelResponseObject interface {
	VisitGetLevelResponse(w http.ResponseWriter) error
}

type GetLevel200ApplicationGeoPlusJSONResponse struct {
	FeatureCollection200ApplicationGeoPlusJSONResponse
}

func (response GetLevel200ApplicationGeoPlusJSONResponse) VisitGetLevelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/geo+json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLevel400Response = BadRequest400Response

func (response GetLevel400Response) VisitGetLevelResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetRoomRequestObject struct {
	Params GetRoomParams
}

type GetRoomResponseObject interface {
	VisitGetRoomResponse(w http.ResponseWriter) error
}

type GetRoom200ApplicationGeoPlusJSONResponse struct {
	FeatureCollection200ApplicationGeoPlusJSONResponse
}

func (response GetRoom200ApplicationGeoPlusJSONResponse) VisitGetRoomResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/geo+json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRoom400Response = BadRequest400Response

func (response GetRoom400Response) VisitGetRoomResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get Buildings
	// (GET /building)
	GetBuilding(ctx context.Context, request GetBuildingRequestObject) (GetBuildingResponseObject, error)
	// Get Doors
	// (GET /door)
	GetDoor(ctx context.Context, request GetDoorRequestObject) (GetDoorResponseObject, error)
	// Get Levels
	// (GET /level)
	GetLevel(ctx context.Context, request GetLevelRequestObject) (GetLevelResponseObject, error)
	// Get Rooms
	// (GET /room)
	GetRoom(ctx context.Context, request GetRoomRequestObject) (GetRoomResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetBuilding operation middleware
func (sh *strictHandler) GetBuilding(w http.ResponseWriter, r *http.Request) {
	var request GetBuildingRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBuilding(ctx, request.(GetBuildingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBuilding")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBuildingResponseObject); ok {
		if err := validResponse.VisitGetBuildingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDoor operation middleware
func (sh *strictHandler) GetDoor(w http.ResponseWriter, r *http.Request, params GetDoorParams) {
	var request GetDoorRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDoor(ctx, request.(GetDoorRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDoor")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDoorResponseObject); ok {
		if err := validResponse.VisitGetDoorResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLevel operation middleware
func (sh *strictHandler) GetLevel(w http.ResponseWriter, r *http.Request, params GetLevelParams) {
	var request GetLevelRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLevel(ctx, request.(GetLevelRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLevel")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLevelResponseObject); ok {
		if err := validResponse.VisitGetLevelResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRoom operation middleware
func (sh *strictHandler) GetRoom(w http.ResponseWriter, r *http.Request, params GetRoomParams) {
	var request GetRoomRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRoom(ctx, request.(GetRoomRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRoom")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRoomResponseObject); ok {
		if err := validResponse.VisitGetRoomResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RWTW/jNhD9KwLbW7UWRUnUx61p2myApBtkewuMgpHGNrciqZCUETfwfy9IyV+xkbhI",
	"e2lvFPn4Zt7jiJwXVCvRKQnSGlS9IA2mU9KA/7hgzT089WBsirGbaMDUmneWK4kqtxyM62gdol+A2V7D",
	"T6ptoXYQMmyqlbQgrRuyrmt5zdxiNAf1wzfjiF6QqRcgmBt9r2GGKvRdtEsrGlZNdBQArdfr8FVSX/u6",
	"BmNmfRtstCCHGklcjJHHDTutOtCWD3rnoARYvfJSuWMVXDKrtJsQrOu4nLvhneJOz+ksr0aSARSiO9Wu",
	"5j61d+ADbB1uklr9ygSgCtlVB25aSfgyQ9XD2yYd852Ld+mup+ErT3z06gWB7AWqHtBrWdNwhCBjtfPH",
	"ma3hqecaGrfBr07Xr3lZ03B3ZKy925u3uoctoXr8BrUvrddJbE7wvOAHocPdKU9PRDqusaMqmQ0QP+YW",
	"hDmzbndCENOard4Qthf+XInbrE6pOjzkI0W1UrpxlT58wjMTXQuoeniI40lGC5olhBBaxrjMw7SYxGmS",
	"4zQtMMUJIdNpuPNhprRg7t9oVP/YusTGZGQvHkG7ZAR7vh7gJESCy93He+4M6Z/ryL6qt00Zf9DzbTnP",
	"l3CEYUqylOC4LJMBRXKC0zTBcZkV6QbmWOI4j2mZ0hGWxklWFHlC8A6VEkJKWmRJkaYjLIvTOMYxpfEe",
	"jsQ0zhJCU0pGWIHzPMnTpMjyHSwheZwlNCtxUYwSMCEYpyUp42yXW0ZpUeQ0T8uRLiE0S2iZFAXNt0qL",
	"MsYFpnmZ56OGhCZFkpY0oWmyhb1XT/sFdTz4F0rsve/9Evw71957Reg2cTlTx2/r59vgXikx47IBHVyB",
	"aphlwQWr/wDZBF86kD/eXQemg5rPxhcVhajlNbgHr3pBcng8bq9/QyHqdYsqtLC2M1UUqQ6kUb2uYaL0",
	"PBo3mUhw+2n8mHSLzsvn1lU8+nz76TgdFKIlaDMkHE/wBPtnqgPJOo4qlPipEHXMLvzJRY89b5vxEZ2D",
	"PZZ9D7bX0gSqty2XYAImm8A55I6cKxnMlA5Y2wYbJnehu3/Wr143qEJXYC82YcLDfmZsSE7d1VtcdLKN",
	"8R1ELwRzzYELEVxsE3BrUaOGLuFjqhzLSUWXjt45qZkAC9r4PoA78qce9AqFmwNvYQnt77xB++U4PKu7",
	"LmssQy4tzN0f4579f8qpEKXnbD7sLY/9vfRWeG+9pI+b62lOunvjA5xl76bu/gMO3wx+eIu1UuLjDjuW",
	"kwa7u+P/Vb733gp/wRvQy43kQ2PvtGp6Hzr46kFHVzXr+GQh9PbqncyVEVr1ls9Wk+fVn9EyjnyLf0h8",
	"o2rWBpewDH6WS66VFOCb9h15FUWtAy2UsVWBCzwwTdd/BQAA//8A9Oh0EQ4AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
