networks:
  internal:

services:
  backend:
    container_name: hmrf_backend
    build:
      target: backend-dev
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    working_dir: /app
    command: go run ./cmd/hmrf -config config/dev.hcl

  frontend:
    container_name: hmrf_frontend
    image: node:22.5.1
    volumes:
      - ./frontend:/app
    working_dir: /app
    environment:
      NODE_ENV: development
    command: npm run dev -- --host 0.0.0.0