networks:
  internal:

services:
  backend:
    container_name: hmrf_backend
    build:
      target: backend-dev
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/app
    ports:
      - 8080:8080

  frontend:
    container_name: hmrf_frontend
    build:
      target: frontend-dev
      dockerfile: dev.Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - /app/.dart_tool
      - /app/build