version: '3.8'

services:
  app:
    image: docker.io/golang
    container_name: hm_roomfinder_geodata_backend
    working_dir: /app
    restart: always
    volumes:
      - .:/app
    command: go run ./cmd/hmroomfinder
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
      - search_db

  search_db:
    image: docker.io/getmeili/meilisearch:v1.8
    container_name: hm_roomfinder_geodata_meilisearch
    restart: always
    environment:
      MEILI_MASTER_KEY: 'hmroomdfindermasterkey'
    ports:
      - "127.0.0.1:7700:7700"


  db:
    image: docker.io/postgis/postgis:12-3.4-alpine
    container_name: hm_roomfinder_geodata_postgis
    restart: always
    environment:
      POSTGRES_USER: hmroomfinder
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hmroomfinder
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pkg/geodata/infrastructure/pgsql/schema.sql:/docker-entrypoint-initdb.d/20-schema.sql
      - ../geodata/pgdump/building.sql:/docker-entrypoint-initdb.d/30-building.sql
      - ../geodata/pgdump/level.sql:/docker-entrypoint-initdb.d/40-level.sql
      - ../geodata/pgdump/room.sql:/docker-entrypoint-initdb.d/50-room.sql
      - ../geodata/pgdump/mockdata.sql:/docker-entrypoint-initdb.d/60-mockdata.sql

  grafana:
    image: docker.io/grafana/grafana
    container_name: hm_roomfinder_grafana
    environment:
      GF_SERVER_ROOT_URL: https://grafana.hmroomfinder.gosmroutify.xyz
      GF_SECURITY_ADMIN_USER: hmroomfinder
      GF_SECURITY_ADMIN_PASSWORD: 12roomfinder34
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - grafanadata:/var/lib/grafana
    depends_on:
      - prometheus

  prometheus:
    image: docker.io/prom/prometheus
    container_name: hm_roomfinder_prometheus
    volumes:
      - ./docker/prometheus:/etc/prometheus
      - prometheusdata:/prometheus
    ports:
      - "127.0.0.1:9000:9090"
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - app

volumes:
  pgdata:
  meilidata:
  grafanadata:
  prometheusdata:
