version: "2"
sql:
  - engine: "postgresql"
    queries: "repository.sql"
    schema: "../schema.sql"
    gen:
      go:
        package: "geodataRepository"
        out: "."
        sql_package: "pgx/v5"
        emit_pointers_for_null_types: true
        emit_json_tags: true
        json_tags_case_style: camel