name: hm_roomfinder
description: "HM-Roomfinder"
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  location: ^6.0.2
  openapi_generator_annotations: ^5.0.2
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0

  geodata_api_sdk:
    path: ../geodata_api_sdk

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner:
  openapi_generator: ^5.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg