global:
  scrape_interval: 10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: api_backend
    static_configs:
      - targets: ["hm_roomfinder_geodata_backend:48080"]